### ISSUE TITLE
[UPDATE] update to minecraft 1.20.4

### ISSUE THREAD

**Issue by Nitroito** [Pandarix/BushyFlowers#8]
i have updated the mod to minecraft 1.20.4

i have no ideia how to create a pull request here (github.com) but i have a pull request ready-to-go on InteliJ
i am available anytime to do so

Regards

**Comment by istir** [comment]
Hello, I'm not a maintainer, but you have to fork this repository, pull it, change stuff, commit them and push. Then, open your forked repository on github, click on `Contribute` and choose `Pull Request`.

**Comment by Pandarix** [comment]
Sorry for my absence in this discussion. There is a 1.20.4 version available on CurseForge and Modrinth.
