### ISSUE TITLE
[UPDATE] 1.21 would be awesome!

### ISSUE THREAD

**Issue by Featherform** [Pandarix/BushyFlowers#9]
Hello! My family and I are in love with this mod, and would be incredibly grateful if it was brought to 1.21! We appreciate your hard work, and understand life comes first, so no rush! Thank you and have a wonderful day

**Comment by Pandarix** [comment]
Thank you so much for your kind message :)!
I'm finally done with a lot of stuff that has been holding me back. So hopefully very soon ^^.

**Comment by Fyoncle** [comment]
> Thank you so much for your kind message :)! I'm finally done with a lot of stuff that has been holding me back. So hopefully very soon ^^.

+1 Here! I would like this mod on 1.21.1 a lot, this mod adding LIFE to my worlds!

**Comment by Pandarix** [comment]
Again, really sorry for the waiting time. Personal stuff is a lot rn. I've updated the mod to 1.20.4 now.
Depending on how much changed regarding to BushierFlowers, the port to 1.21 should be very very soon.

**Comment by Fyoncle** [comment]
> Again, really sorry for the waiting time. Personal stuff is a lot rn. I've updated the mod to 1.20.4 now. Depending on how much changed regarding to BushierFlowers, the port to 1.21 should be very very soon.

Thank you! :D

**Comment by Pandarix** [comment]
Update is already out, the port was actually quite easy with this small of a mod :D

**Comment by Fyoncle** [comment]
> Update is already out, the port was actually quite easy with this small of a mod :D

YOU'RE AWESOME! ❤️

**Comment by Pandarix** [comment]
<3
You can already download it on Modrinth, CurseForge may take a moment because of file validation and scans.

**Comment by Featherform** [comment]
Thank you SOOO much! <3
